name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx (for building multi-platform images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub (ensure you store your Docker Hub credentials in GitHub Secrets)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t myusername/myapp:${{ github.sha }} .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push myusername/myapp:${{ github.sha }}

    # SSH into your server (replace with your details) and deploy the container
    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Add the SSH private key to the SSH agent
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        eval $(ssh-agent -s)
        ssh-add private_key.pem

        # SSH into the server and pull the latest Docker image and restart the container
        ssh -o StrictHostKeyChecking=no username@your-server-ip << 'EOF'
          docker pull myusername/myapp:${{ github.sha }}
          docker stop myapp-container || true
          docker rm myapp-container || true
          docker run -d --name myapp-container -p 80:80 myusername/myapp:${{ github.sha }}
        EOF
